name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "2.x"

      - name: Build the project
        run: |
          deno task build

      - name: Deploy to gh-pages
        run: |
          # Move into a clean deployment folder
          mkdir deploy
          cp -r _fresh/* deploy/
          
          # Go into deploy folder
          cd deploy
          
          # Init a fresh git repo
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          
          echo "We done it"
          
          # Force push to gh-pages branch
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:gh-pages
